## **1.1 创建NumPy数组**

### **1.1.1 从Python列表创建数组**

首先，我们可以用`np.array`将Python列表转变为NumPy数组：

In [2]:
import numpy as np

# 整型数组
np.array([1, 4, 2, 5, 3])

array([1, 4, 2, 5, 3])

请注意，不同于Python列表，NumPy数组只能包含同一类型的数据。如果类型不一样，NumPy会向上转换（如果可行）。以下的整型将被转换为浮点型：

In [3]:
np.array([3.14, 4, 2, 3])

array([3.14, 4.  , 2.  , 3.  ])

如果希望明确设置数组的数据类型，我们可以用`dtype`关键字：

In [4]:
np.array([1, 2, 3, 4], dtype='float32')

array([1., 2., 3., 4.], dtype=float32)

最后，不同于Python列表，NumPy数组可以被指定为多维的。以下是使用列表的列表来创建多维数组的一种方法：

In [5]:
# 嵌套列表构成的多维数组
# 更准确的说，应该是生成器的列表，列表解析中有三个range生成器
# 分别是range(2, 5)，range(4, 7)和range(6, 9)
np.array([range(i, i+3) for i in [2, 4, 6]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

内层的列表会被当作二维数组的行。用以下代码也可以创建多维数组：

In [6]:
np.array([[2, 3, 4],
          [4, 5, 6],
          [6, 7, 8]])

array([[2, 3, 4],
       [4, 5, 6],
       [6, 7, 8]])

### **1.1.2 从头创建数组**

面对大型数组的时候，用NumPy内置的方法从头创建数组是一种更高效的方法：

In [7]:
# 创建一个长度为10的数组，数组的值都是0
np.zeros(10, dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [8]:
# 创建一个3×5的浮点型数组，数组的值都是1
np.ones((3, 5), dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [9]:
# 创建一个3×5的浮点型数组，数组的值都是3.14
np.full((3, 5), 3.14)

array([[3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14],
       [3.14, 3.14, 3.14, 3.14, 3.14]])

In [10]:
# 创建一个值为线性序列的数组
# 从0开始，到20结束——[0, 20)，步长为2
# 该函数与Python内置的range()函数类似
np.arange(0, 20, 2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
# 创建一段序列值，其中元素按照区域进行线性（平均）划分
# 起始值是0（包含），结束值是1（包含），共5个元素
np.linspace(0, 1, 5)

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

In [12]:
# random.random随机分布创建数组
# 随机值范围为[0, 1)
# (3, 3)是维度说明，二维数组3行3列
np.random.random((3, 3))

array([[0.31742634, 0.86924829, 0.91640036],
       [0.71967636, 0.72578893, 0.23383613],
       [0.69082914, 0.88114793, 0.88974354]])

In [13]:
# random.normal正态分布创建数组
# 均值0，标准差1
# (3, 3)是维度说明，二维数组3行3列
np.random.normal(0, 1, (3, 3))

array([[ 0.14082601,  0.4470323 , -0.82704845],
       [-1.02814448, -0.22644973,  0.63003269],
       [ 1.01662242,  0.56939298, -0.07588441]])

In [14]:
# random.randint随机整数创建数组
# 随机数范围[0, 10)
np.random.randint(0, 10, (3, 3))

array([[6, 5, 2],
       [4, 5, 9],
       [4, 3, 3]])

In [15]:
# 创建一个3×3的单位矩阵
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [16]:
# 创建一个由3个整数组成的未初始化的数组
# 数组元素的值保持为原有的内存空间值
np.empty(3)

array([1., 1., 1.])

### **1.1.3 NumPy标准数据类型**

NumPy数组仅包含一种类型的数据，因此详细了解这些数据类型及其限制是非常重要的。由于NumPy主要是用C语言编写的，所以C、Fortran和其他类似语言的用户会比较熟悉这些数据类型。

当构建一个数组时，我们可以用一个字符串参数来指定数据类型：

In [17]:
np.zeros(10, dtype='int16')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

也可以用相关的NumPy对象来指定：

In [18]:
np.zeros(10, dtype=np.int16)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int16)

下表列出了标准NumPy数据类型：

| 数据类型 | 描述 |
|-----------|------------|
| bool_     | 布尔值（True 或 False），用一个字节存储 |
| int_      | 默认整型（类似于C语言的long，通常情况下是int64或int32）| 
| intc      | 同C语言中的int相同（通常是int32或int64）| 
| intp      | 用于索引值的整型（和C语言中的ssize_t相同，通常情况下是int32或int64）|
| int8      | 字节（1字节，-128 ~ 127）| 
| int16     | 整型（2字节，-32768 ~ 32767）|
| int32     | 整型（4字节，-2147483648 ~ 2147483647）|
| int64     | 整型（8字节，-9223372036854775808 ~ 9223372036854775807）| 
| uint8     | 无符号整型（0 ~ 255）| 
| uint16    | 无符号整型（0 ~ 65535）| 
| uint32    | 无符号整型（0 ~ 4294967295）| 
| uint64    | 无符号整型（0 ~ 18446744073709551615）| 
| float_    | float64的简化形式 | 
| float16   | 半精度浮点数：1比特符号位，5比特指数位，10比特尾数位 | 
| float32   | 单精度浮点数：1比特符号位，8比特指数位，23比特尾数位| 
| float64   | 双精度浮点数：1比特符号位，11比特指数位，52比特尾数位| 
| complex_  | complex128的简化形式 |
| complex64 | 复数，由2个单精度浮点数组成 | 
| complex128 | 复数，由2个双精度浮点数组成 | 

我们还可以进行更高级的数据类型指定，例如指定高位字节数或低位字节数；NumPy也支持复合数据类型（这部分将在[结构化数据：NumPy的结构化数组](./1.9%20结构化数据：NumPy的结构化数组.ipynb)中介绍）。更多的信息可以在[NumPy官网](http://numpy.org)或[NumPy在线文档](https://numpy.org/doc/stable/)中查看。